'use client'
import { useEffect,useMemo,useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { NovaHeader } from '@/components/shared/nova-header'
type Prefs={kudos:boolean;comments:boolean;replies:boolean;follows:boolean;chapters:boolean;collaborations:boolean;moderation:boolean;email_digest:'OFF'|'DAILY'|'WEEKLY'}
const defaults:Prefs={kudos:true,comments:true,replies:true,follows:true,chapters:true,collaborations:true,moderation:true,email_digest:'OFF'}
export function NotificationSettings(){
 const supabase=useMemo(()=>createClient(),[]);const [prefs,setPrefs]=useState<Prefs>(defaults);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('')
 useEffect(()=>{void(async()=>{const user=(await supabase.auth.getUser()).data.user;if(!user){setLoading(false);return}const {data}=await supabase.from('notification_preferences').select('*').eq('user_id',user.id).maybeSingle();if(data)setPrefs({...defaults,...data} as Prefs);setLoading(false)})()},[supabase])
 async function save(){const user=(await supabase.auth.getUser()).data.user;if(!user)return;const {error}=await supabase.from('notification_preferences').upsert({user_id:user.id,...prefs,updated_at:new Date().toISOString()});setMessage(error?error.message:'Preferências salvas.')}
 if(loading)return <><NovaHeader title="Notificações"/><main className="notification-settings-page"><div className="studio-loading"><span/><h1>Carregando…</h1></div></main></>
 const toggles=[['kudos','Kudos','Quando alguém deixar kudos nas suas obras.'],['comments','Comentários','Novos comentários nas suas histórias.'],['replies','Respostas','Respostas às suas conversas.'],['follows','Seguidores','Novos seguidores no perfil.'],['chapters','Novos capítulos','Atualizações de obras que você acompanha.'],['collaborations','Colaboração','Convites, revisões e contribuições.'],['moderation','Moderação','Atualizações sobre denúncias e ações da equipe.']] as const
 return <><NovaHeader title="Notificações"/><main className="notification-settings-page"><header><p className="eyebrow">Preferências</p><h1>Você escolhe o que merece sua atenção.</h1><p>Controle cada categoria separadamente.</p></header><section>{toggles.map(([key,title,desc])=><label key={key}><span><strong>{title}</strong><small>{desc}</small></span><input type="checkbox" checked={prefs[key]} onChange={e=>setPrefs(cur=>({...cur,[key]:e.target.checked}))}/></label>)}<label><span><strong>Resumo por e-mail</strong><small>Base preparada para SMTP/digests futuros.</small></span><select value={prefs.email_digest} onChange={e=>setPrefs(cur=>({...cur,email_digest:e.target.value as Prefs['email_digest']}))}><option value="OFF">Desativado</option><option value="DAILY">Diário</option><option value="WEEKLY">Semanal</option></select></label></section><button className="primary-button" onClick={()=>void save()}>Salvar preferências</button>{message?<div className="reader-page-toast" role="status">{message}</div>:null}</main></>
}
