'use client'

import type { DragEvent } from 'react'
import type { CloudDraftChapter } from '@/lib/cloud-drafts'

type Tab = 'overview' | 'chapters' | 'plan' | 'notes' | 'versions' | 'tools' | 'beta'

export function WriterExperienceView({ ctx }: { ctx: any }) {
  const { supabase, open, setOpen, tab, setTab, draft, setDraft, state, setState, loading, setLoading, notice, setNotice, busy, setBusy, selectedChapterId, setSelectedChapterId, previewChapter, setPreviewChapter, compareVersion, setCompareVersion, assetKind, setAssetKind, assetTitle, setAssetTitle, assetBody, setAssetBody, editingAsset, setEditingAsset, noteBody, setNoteBody, noteAnchor, setNoteAnchor, find, setFind, replaceWith, setReplaceWith, searchHits, setSearchHits, consistency, setConsistency, betaLabel, setBetaLabel, importing, setImporting, load, selectedChapter, totalWords, today, todayWords, weekWords, streak, saveGoals, saveChapterMeta, patchChapter, reorder, saveAsset, editAsset, deleteAsset, addNote, toggleNote, snapshot, restoreVersion, searchEverywhere, replaceEverywhere, importAsChapters, runConsistency, createBetaInvite, revokeBeta, consistencyCount, ASSET_KINDS, assetLabel, stageLabel, pct, dateTimeLocal, stripWriterHtml, renderWordDiff } = ctx
  return <>
    <button className={`writer-xp-launcher ${open ? 'active' : ''}`} type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open}><span>✦</span><b>Workspace</b></button>
    <aside className={`writer-xp-dock ${open ? 'open' : ''}`} aria-label="Writer Workspace">
      <header className="writer-xp-head"><div><span>WRITER EXPERIENCE</span><strong>{draft?.title || 'Sua história'}</strong></div><button type="button" onClick={() => setOpen(false)}>×</button></header>
      <nav className="writer-xp-tabs" aria-label="Ferramentas do escritor">
        {([['overview','Visão'],['chapters','Capítulos'],['plan','Planejar'],['notes','Notas'],['versions','Versões'],['tools','Ferramentas'],['beta','Beta']] as Array<[Tab,string]>).map(([value,label]) => <button type="button" className={tab === value ? 'active' : ''} key={value} onClick={() => setTab(value)}>{label}</button>)}
      </nav>
      {loading ? <div className="writer-xp-loading">Carregando workspace…</div> : null}
      {!loading && draft ? <div className="writer-xp-body">
        {tab === 'overview' ? <section className="writer-xp-section">
          <div className="writer-xp-kpis"><article><strong>{todayWords.toLocaleString('pt-BR')}</strong><span>palavras hoje</span></article><article><strong>{streak}</strong><span>dias de sequência</span></article><article><strong>{totalWords.toLocaleString('pt-BR')}</strong><span>na obra</span></article></div>
          <label>Meta diária<input type="number" min="0" value={draft.daily_word_goal || 0} onChange={(e) => setDraft({ ...draft, daily_word_goal: Number(e.target.value) })} /></label>
          <div className="writer-xp-progress"><span><b>Hoje</b><small>{pct(todayWords, Number(draft.daily_word_goal || 0))}%</small></span><i><b style={{ width: `${pct(todayWords, Number(draft.daily_word_goal || 0))}%` }} /></i></div>
          <label>Meta semanal<input type="number" min="0" value={draft.weekly_word_goal || 0} onChange={(e) => setDraft({ ...draft, weekly_word_goal: Number(e.target.value) })} /></label>
          <div className="writer-xp-progress"><span><b>7 dias</b><small>{pct(weekWords, Number(draft.weekly_word_goal || 0))}%</small></span><i><b style={{ width: `${pct(weekWords, Number(draft.weekly_word_goal || 0))}%` }} /></i></div>
          <label>Meta da história<input type="number" min="1" placeholder="Ex.: 80000" value={draft.project_word_goal || ''} onChange={(e) => setDraft({ ...draft, project_word_goal: e.target.value ? Number(e.target.value) : null })} /></label>
          {draft.project_word_goal ? <div className="writer-xp-progress"><span><b>Projeto</b><small>{pct(totalWords, Number(draft.project_word_goal))}%</small></span><i><b style={{ width: `${pct(totalWords, Number(draft.project_word_goal))}%` }} /></i></div> : null}
          <button className="writer-xp-primary" type="button" disabled={busy} onClick={() => void saveGoals()}>Salvar metas</button>
          <div className="writer-xp-activity"><strong>Últimos 30 dias</strong><div>{Array.from({ length: 30 }, (_, index) => { const day = new Date(); day.setDate(day.getDate() - (29 - index)); const key = day.toISOString().slice(0,10); const amount = state.activity.find((row) => row.activity_date === key)?.words_added || 0; return <i key={key} title={`${key}: ${amount} palavras`} data-level={amount > 1500 ? '4' : amount > 750 ? '3' : amount > 250 ? '2' : amount > 0 ? '1' : '0'} /> })}</div></div>
        </section> : null}

        {tab === 'chapters' ? <section className="writer-xp-section"><p className="writer-xp-help">Arraste os cartões para reorganizar. Metadados de planejamento não aparecem para leitores.</p><div className="writer-xp-chapter-list">{draft.chapters.map((chapter) => <article key={chapter.id} draggable onDragStart={(event: DragEvent<HTMLElement>) => event.dataTransfer.setData('text/chapter-id', chapter.id)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void reorder(event.dataTransfer.getData('text/chapter-id'), chapter.id) }} className={selectedChapter?.id === chapter.id ? 'selected' : ''} onClick={() => setSelectedChapterId(chapter.id)}><header><b>☷ {String(chapter.position).padStart(2,'0')}</b><strong>{chapter.title || `Capítulo ${chapter.position}`}</strong><span>{stageLabel(chapter.stage || 'DRAFT')}</span></header>{selectedChapter?.id === chapter.id ? <div className="writer-xp-chapter-fields"><label>Etapa<select value={chapter.stage || 'DRAFT'} onChange={(e) => patchChapter(chapter.id, { stage: e.target.value as CloudDraftChapter['stage'] })}><option value="IDEA">Ideia</option><option value="DRAFT">Rascunho</option><option value="REVISION">Revisão</option><option value="READY">Pronto</option></select></label><label>POV<input value={chapter.pov || ''} onChange={(e) => patchChapter(chapter.id, { pov: e.target.value })} placeholder="Ex.: 1ª pessoa · Lia" /></label><label>Meta de palavras<input type="number" min="1" value={chapter.target_words || ''} onChange={(e) => patchChapter(chapter.id, { target_words: e.target.value ? Number(e.target.value) : null })} /></label><label>Publicar/agendar<input type="datetime-local" value={dateTimeLocal(chapter.scheduled_for)} onChange={(e) => patchChapter(chapter.id, { scheduled_for: e.target.value ? new Date(e.target.value).toISOString() : null })} /></label><label className="span-2">Sinopse privada<textarea rows={3} value={chapter.synopsis || ''} onChange={(e) => patchChapter(chapter.id, { synopsis: e.target.value })} placeholder="O que precisa acontecer neste capítulo?" /></label><div className="writer-xp-row span-2"><button type="button" onClick={() => setPreviewChapter(chapter)}>Prévia</button><button className="writer-xp-primary" type="button" onClick={() => void saveChapterMeta(chapter)}>Salvar capítulo</button></div></div> : null}</article>)}</div></section> : null}

        {tab === 'plan' ? <section className="writer-xp-section"><div className="writer-xp-kind-row">{ASSET_KINDS.map((kind) => <button type="button" className={assetKind === kind ? 'active' : ''} key={kind} onClick={() => { setAssetKind(kind); setEditingAsset(null); setAssetTitle(''); setAssetBody('') }}>{assetLabel(kind)}</button>)}</div><label>Título<input value={assetTitle} onChange={(e) => setAssetTitle(e.target.value)} placeholder={assetKind === 'CHARACTER' ? 'Nome do personagem' : assetKind === 'SNIPPET' ? 'Nome do trecho' : 'Título'} /></label><label>Conteúdo<textarea rows={6} value={assetBody} onChange={(e) => setAssetBody(e.target.value)} placeholder="Anotações, detalhes, cronologia, descrição ou trecho reutilizável…" /></label><div className="writer-xp-row"><button type="button" onClick={() => { setEditingAsset(null); setAssetTitle(''); setAssetBody('') }}>Limpar</button><button className="writer-xp-primary" type="button" disabled={busy} onClick={() => void saveAsset()}>{editingAsset ? 'Atualizar' : 'Adicionar'}</button></div><div className="writer-xp-assets">{state.assets.filter((asset) => asset.kind === assetKind).map((asset) => <article key={asset.id}><div><strong>{asset.title}</strong><p>{asset.body || 'Sem detalhes.'}</p></div><button type="button" onClick={() => editAsset(asset)}>Editar</button><button type="button" onClick={() => void deleteAsset(asset.id)}>×</button></article>)}</div></section> : null}

        {tab === 'notes' ? <section className="writer-xp-section"><label>Capítulo<select value={selectedChapter?.id || ''} onChange={(e) => setSelectedChapterId(e.target.value)}>{draft.chapters.map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.position}. {chapter.title || 'Sem título'}</option>)}</select></label><label>Trecho de referência<input value={noteAnchor} onChange={(e) => setNoteAnchor(e.target.value)} placeholder="Opcional: cole a frase que quer revisar" /></label><label>Nota privada<textarea rows={4} value={noteBody} onChange={(e) => setNoteBody(e.target.value)} placeholder="Reescrever esta cena, checar continuidade, foreshadowing…" /></label><button className="writer-xp-primary" type="button" onClick={() => void addNote()}>Adicionar nota</button><div className="writer-xp-notes">{state.annotations.map((note) => <article className={note.resolved ? 'resolved' : ''} key={note.id}>{note.anchor_text ? <blockquote>{note.anchor_text}</blockquote> : null}<p>{note.body}</p><button type="button" onClick={() => void toggleNote(note.id, !note.resolved)}>{note.resolved ? 'Reabrir' : 'Resolver'}</button></article>)}</div></section> : null}

        {tab === 'versions' ? <section className="writer-xp-section"><div className="writer-xp-row"><select value={selectedChapter?.id || ''} onChange={(e) => setSelectedChapterId(e.target.value)}>{draft.chapters.map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.position}. {chapter.title || 'Sem título'}</option>)}</select><button className="writer-xp-primary" type="button" onClick={() => void snapshot()}>Criar versão</button></div><p className="writer-xp-help">O Writer também cria checkpoints automáticos durante alterações relevantes.</p><div className="writer-xp-versions">{state.versions.filter((version) => !selectedChapter || version.chapter_id === selectedChapter.id).map((version) => <article key={version.id}><div><strong>{new Date(version.created_at).toLocaleString('pt-BR')}</strong><small>{version.source} · revisão {version.revision} · {Number(version.word_count || 0).toLocaleString('pt-BR')} palavras</small></div><button type="button" onClick={() => setCompareVersion(version)}>Comparar</button><button type="button" onClick={() => void restoreVersion(version.id)}>Restaurar</button></article>)}</div></section> : null}

        {tab === 'tools' ? <section className="writer-xp-section"><h3>Importar documento inteiro</h3><p className="writer-xp-help">DOCX, PDF, TXT, Markdown, HTML e RTF passam pelo importador atual. Títulos H1/H2 viram capítulos automaticamente; sem títulos, o arquivo entra como um capítulo.</p><label className="writer-xp-file">Importar como capítulos<input type="file" accept=".docx,.pdf,.txt,.md,.markdown,.html,.htm,.rtf,.doc" disabled={importing} onChange={(event) => { const file = event.target.files?.[0]; event.target.value=''; if (file) void importAsChapters(file) }}/></label><hr/><h3>Busca na obra inteira</h3><label>Encontrar<input value={find} onChange={(e) => setFind(e.target.value)} placeholder="Nome, termo ou frase" /></label><label>Substituir por<input value={replaceWith} onChange={(e) => setReplaceWith(e.target.value)} /></label><div className="writer-xp-row"><button type="button" onClick={() => void searchEverywhere()}>Buscar</button><button type="button" onClick={() => void replaceEverywhere(false)}>Pré-calcular</button><button className="writer-xp-primary" type="button" onClick={() => void replaceEverywhere(true)}>Substituir</button></div>{searchHits.length ? <div className="writer-xp-search-hits">{searchHits.map((hit) => <button type="button" key={hit.chapter_id} onClick={() => setSelectedChapterId(hit.chapter_id)}><strong>Cap. {hit.position} · {hit.title || 'Sem título'}</strong><span>{hit.matches} ocorrência(s)</span></button>)}</div> : null}<hr/><div className="writer-xp-row"><div><h3>Verificador de consistência</h3><p className="writer-xp-help">Heurísticas simples: títulos repetidos/ausentes, capítulos vazios ou muito curtos e estados incoerentes.</p></div><button type="button" onClick={() => void runConsistency()}>Analisar</button></div>{consistency ? <div className={`writer-xp-consistency ${consistencyCount ? 'warn' : 'ok'}`}><strong>{consistencyCount ? `${consistencyCount} ponto(s) para revisar` : 'Nenhuma inconsistência básica encontrada'}</strong>{Object.entries(consistency).map(([key,value]) => Array.isArray(value) && value.length ? <span key={key}>{key.replaceAll('_',' ')}: {value.length}</span> : null)}</div> : null}</section> : null}

        {tab === 'beta' ? <section className="writer-xp-section"><p className="writer-xp-help">Crie um link privado. O leitor precisa entrar no Archive Nova e reivindicar o convite antes de ver o rascunho.</p><label>Nome do convite<input value={betaLabel} onChange={(e) => setBetaLabel(e.target.value)} placeholder="Ex.: revisão da Ana" /></label><button className="writer-xp-primary" type="button" onClick={() => void createBetaInvite()}>Criar link beta</button><div className="writer-xp-invites">{state.beta_invites.map((invite) => <article key={invite.id}><div><strong>{invite.label || 'Leitor beta'}</strong><small>{invite.status === 'ACTIVE' ? `Válido até ${new Date(invite.expires_at).toLocaleDateString('pt-BR')}` : 'Revogado'}{invite.reader_id ? ' · reivindicado' : ''}</small></div>{invite.status === 'ACTIVE' ? <><button type="button" onClick={() => void navigator.clipboard.writeText(`${window.location.origin}/beta/${invite.token}`).then(() => setNotice('Link copiado.'))}>Copiar</button><button type="button" onClick={() => void revokeBeta(invite.id)}>Revogar</button></> : null}</article>)}</div>{state.beta_feedback.length ? <><h3>Feedback beta</h3><div className="writer-xp-feedback">{state.beta_feedback.map((feedback) => <article key={feedback.id}>{feedback.anchor_text ? <blockquote>{feedback.anchor_text}</blockquote> : null}<p>{feedback.body}</p><small>{new Date(feedback.created_at).toLocaleString('pt-BR')}</small></article>)}</div></> : null}</section> : null}
      </div> : null}
      {notice ? <div className="writer-xp-notice" role="status">{notice}</div> : null}
    </aside>
    {compareVersion && selectedChapter ? <div className="writer-xp-preview writer-xp-diff" role="dialog" aria-modal="true"><article><header><div><span>MODO REVISÃO</span><h2>Mudanças desde {new Date(compareVersion.created_at).toLocaleString('pt-BR')}</h2></div><button type="button" onClick={() => setCompareVersion(null)}>×</button></header><div className="writer-xp-diff-grid"><section><b>VERSÃO ANTERIOR</b><div>{stripWriterHtml(compareVersion.content_html)}</div></section><section><b>VERSÃO ATUAL · alterações marcadas</b><div>{renderWordDiff(compareVersion.content_html, selectedChapter.content_html)}</div></section></div></article></div> : null}
    {previewChapter ? <div className="writer-xp-preview" role="dialog" aria-modal="true"><article><header><div><span>PRÉVIA DO LEITOR</span><h2>{previewChapter.title || `Capítulo ${previewChapter.position}`}</h2></div><button type="button" onClick={() => setPreviewChapter(null)}>×</button></header><div className="writer-xp-preview-text" dangerouslySetInnerHTML={{ __html: previewChapter.content_html }} /><footer>{stripWriterHtml(previewChapter.content_html).split(/\s+/u).filter(Boolean).length.toLocaleString('pt-BR')} palavras</footer></article></div> : null}
  </>
}
