-- ArchiveNova v4.8 — NovaDrop 02: Trust & Spectacle
-- NovaShield: explainable pseudo-AI moderation
-- NovaCare: first-party support/ticket center
-- ArchiveNova Classics: curated public-domain books

-- =============================================================================
-- NovaShield
-- =============================================================================

alter table public.works
  add column if not exists moderation_risk_score smallint not null default 0
    check (moderation_risk_score between 0 and 100),
  add column if not exists moderation_state varchar(20) not null default 'CLEAR'
    check (moderation_state in ('CLEAR','WATCH','REVIEW','URGENT')),
  add column if not exists moderation_scan_pending boolean not null default true,
  add column if not exists last_moderation_scan_at timestamptz;

create index if not exists works_moderation_queue_idx
  on public.works(moderation_scan_pending, moderation_risk_score desc, updated_at desc)
  where deleted_at is null;

create table if not exists public.moderation_scan_rules (
  id uuid primary key default gen_random_uuid(),
  code varchar(80) not null unique,
  category varchar(40) not null check (category in (
    'CHILD_SAFETY','TERRORISM','HATE','SELF_HARM','DOXXING','RATING_MISMATCH','OTHER'
  )),
  label varchar(160) not null,
  detector varchar(24) not null default 'CO_OCCURRENCE'
    check (detector in ('REGEX','CO_OCCURRENCE','METADATA')),
  pattern_a text not null,
  pattern_b text,
  max_distance integer not null default 180 check (max_distance between 20 and 1200),
  weight smallint not null check (weight between 1 and 100),
  enabled boolean not null default true,
  description text,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moderation_scans (
  id uuid primary key default gen_random_uuid(),
  work_id uuid not null references public.works(id) on delete cascade,
  requested_by uuid references public.profiles(id) on delete set null,
  trigger_source varchar(40) not null default 'MANUAL',
  engine_version varchar(40) not null default 'NOVASHIELD_RULES_V1',
  score smallint not null default 0 check (score between 0 and 100),
  severity varchar(20) not null default 'CLEAR'
    check (severity in ('CLEAR','WATCH','REVIEW','URGENT')),
  recommended_action varchar(30) not null default 'NONE'
    check (recommended_action in ('NONE','WATCH','HUMAN_REVIEW','URGENT_REVIEW')),
  review_status varchar(30) not null default 'UNREVIEWED'
    check (review_status in ('UNREVIEWED','FALSE_POSITIVE','CONFIRMED_SAFE','ACTION_REQUIRED')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  review_note text,
  reviewed_at timestamptz,
  signals_count integer not null default 0 check (signals_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.moderation_scan_hits (
  id bigint generated by default as identity primary key,
  scan_id uuid not null references public.moderation_scans(id) on delete cascade,
  rule_id uuid not null references public.moderation_scan_rules(id) on delete restrict,
  category varchar(40) not null,
  label varchar(160) not null,
  weight smallint not null,
  match_count integer not null default 1 check (match_count > 0),
  created_at timestamptz not null default now(),
  unique(scan_id, rule_id)
);

create index if not exists moderation_scans_work_created_idx
  on public.moderation_scans(work_id, created_at desc);
create index if not exists moderation_scans_queue_idx
  on public.moderation_scans(review_status, severity, created_at desc);
create index if not exists moderation_hits_scan_idx
  on public.moderation_scan_hits(scan_id);
create index if not exists moderation_rules_updated_by_idx
  on public.moderation_scan_rules(updated_by)
  where updated_by is not null;

alter table public.moderation_scan_rules enable row level security;
alter table public.moderation_scans enable row level security;
alter table public.moderation_scan_hits enable row level security;

revoke all on public.moderation_scan_rules from anon, authenticated;
revoke all on public.moderation_scans from anon, authenticated;
revoke all on public.moderation_scan_hits from anon, authenticated;

grant all on public.moderation_scan_rules to service_role;
grant all on public.moderation_scans to service_role;
grant all on public.moderation_scan_hits to service_role;

insert into public.moderation_scan_rules(
  code,category,label,detector,pattern_a,pattern_b,max_distance,weight,description
)
values
  (
    'CHILD_SAFETY_SEXUAL_CONTEXT','CHILD_SAFETY','Possível conteúdo sexual envolvendo menores','CO_OCCURRENCE',
    '(crian[cç]a|menor( de idade)?|pr[eé]-?adolescente|adolescente)',
    '(sexual|sexo|estupro|pornograf|nudez|er[oó]tic|expl[ií]cit)',
    220,90,
    'Sinaliza coocorrência de referências a menores e contexto sexual. Exige revisão humana; não aplica punição automática.'
  ),
  (
    'TERRORISM_RECRUITMENT','TERRORISM','Possível promoção ou recrutamento extremista','CO_OCCURRENCE',
    '(terroris|extremis|atentado|organiza[cç][aã]o armada)',
    '(recrut|propaganda|glorific|manual|instru[cç][aã]o)',
    260,75,
    'Prioriza material que combina referência terrorista/extremista com sinais de promoção, instrução ou recrutamento.'
  ),
  (
    'SELF_HARM_PROMOTION','SELF_HARM','Possível incentivo ou instrução de autoagressão','CO_OCCURRENCE',
    '(suic[ií]d|automutila|autoagress)',
    '(incentiv|encoraj|manual|instru[cç][aã]o|como fazer)',
    220,70,
    'Distingue simples menção temática de linguagem potencialmente promocional/instrutiva.'
  ),
  (
    'HATE_DEHUMANIZATION','HATE','Possível desumanização ou incitação contra grupo protegido','CO_OCCURRENCE',
    '(ra[cç]a|etnia|relig|nacionalidade|g[eê]nero|orienta[cç][aã]o)',
    '(extermin|subuman|inferior|expuls|eliminar)',
    220,65,
    'Sinal de risco para revisão contextual. Literatura histórica ou crítica pode gerar falso positivo.'
  ),
  (
    'DOXXING_CPF','DOXXING','Possível CPF exposto','REGEX',
    '([0-9]{3}\.?){3}-?[0-9]{2}',
    null,180,35,
    'Detecta formato semelhante a CPF; pode haver números fictícios e por isso não gera ação automática.'
  ),
  (
    'DOXXING_PHONE','DOXXING','Possível telefone pessoal exposto','REGEX',
    '(\+?55[[:space:]]*)?(\(?[1-9][0-9]\)?[[:space:]]*)?9?[0-9]{4}[-[:space:]]?[0-9]{4}',
    null,180,25,
    'Detecta formato semelhante a telefone brasileiro.'
  ),
  (
    'RATING_EXPLICIT','RATING_MISMATCH','Possível classificação etária incompatível','METADATA',
    '(sexo expl[ií]cito|conte[uú]do sexual expl[ií]cito|estupro|pornograf|gore|tortura)',
    null,180,35,
    'Sinaliza conteúdo sensível em obra marcada como GENERAL ou TEEN.'
  )
on conflict(code) do update
set
  category=excluded.category,
  label=excluded.label,
  detector=excluded.detector,
  pattern_a=excluded.pattern_a,
  pattern_b=excluded.pattern_b,
  max_distance=excluded.max_distance,
  weight=excluded.weight,
  description=excluded.description,
  updated_at=now();

drop trigger if exists moderation_scan_rules_updated_at on public.moderation_scan_rules;
create trigger moderation_scan_rules_updated_at
before update on public.moderation_scan_rules
for each row execute function public.set_updated_at();

create or replace function public.novashield_mark_work_pending()
returns trigger
language plpgsql
set search_path=public,pg_temp
as $$
begin
  if tg_op='INSERT' then
    new.moderation_scan_pending:=true;
  elsif
    new.title is distinct from old.title
    or new.summary is distinct from old.summary
    or new.rating is distinct from old.rating
    or new.status is distinct from old.status
    or new.visibility is distinct from old.visibility
  then
    new.moderation_scan_pending:=true;
  end if;
  return new;
end;
$$;

drop trigger if exists works_novashield_pending on public.works;
create trigger works_novashield_pending
before insert or update of title,summary,rating,status,visibility on public.works
for each row execute function public.novashield_mark_work_pending();

create or replace function public.novashield_mark_chapter_work_pending()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare wid uuid;
begin
  wid:=case when tg_op='DELETE' then old.work_id else new.work_id end;
  update public.works
  set moderation_scan_pending=true
  where id=wid;
  if tg_op='DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists chapters_novashield_pending on public.chapters;
create trigger chapters_novashield_pending
after insert or delete or update of title,content,status on public.chapters
for each row execute function public.novashield_mark_chapter_work_pending();

revoke execute on function public.novashield_mark_work_pending() from public,anon,authenticated;
revoke execute on function public.novashield_mark_chapter_work_pending() from public,anon,authenticated;

create or replace function public.novashield_scan_work(
  target_work uuid,
  scan_source text default 'MANUAL'
)
returns jsonb
language plpgsql
security definer
set search_path=public,auth,pg_temp
as $$
declare
  uid uuid:=auth.uid();
  work_row public.works%rowtype;
  scan_id uuid;
  rule_row public.moderation_scan_rules%rowtype;
  metadata_text text;
  chapter_hits integer;
  metadata_hit boolean;
  regex_pattern text;
  total_score integer:=0;
  total_signals integer:=0;
  severity_value text:='CLEAR';
  action_value text:='NONE';
  categories text[];
begin
  select * into work_row
  from public.works
  where id=target_work and deleted_at is null;

  if work_row.id is null then
    raise exception 'WORK_NOT_FOUND' using errcode='P0002';
  end if;

  if uid is null or (work_row.creator_id<>uid and not public.is_staff()) then
    raise exception 'NO_ACCESS' using errcode='42501';
  end if;

  metadata_text:=lower(regexp_replace(
    coalesce(work_row.title,'')||' '||coalesce(work_row.summary,''),
    '[[:space:]]+',' ','g'
  ));

  insert into public.moderation_scans(
    work_id,requested_by,trigger_source,engine_version
  )
  values(
    target_work,uid,left(upper(coalesce(scan_source,'MANUAL')),40),'NOVASHIELD_RULES_V1'
  )
  returning id into scan_id;

  for rule_row in
    select * from public.moderation_scan_rules where enabled order by weight desc
  loop
    metadata_hit:=false;
    chapter_hits:=0;

    if rule_row.detector='REGEX' then
      metadata_hit:=metadata_text ~* rule_row.pattern_a;

      select count(*)::integer into chapter_hits
      from public.chapters c
      where c.work_id=target_work
        and c.status='PUBLISHED'
        and lower(regexp_replace(coalesce(c.title,'')||' '||coalesce(c.content,''),'[[:space:]]+',' ','g')) ~* rule_row.pattern_a;

    elsif rule_row.detector='CO_OCCURRENCE' then
      regex_pattern:=
        '('||rule_row.pattern_a||').{0,'||rule_row.max_distance||'}('||coalesce(rule_row.pattern_b,'a^')||')'
        ||'|('||coalesce(rule_row.pattern_b,'a^')||').{0,'||rule_row.max_distance||'}('||rule_row.pattern_a||')';

      metadata_hit:=metadata_text ~* regex_pattern;

      select count(*)::integer into chapter_hits
      from public.chapters c
      where c.work_id=target_work
        and c.status='PUBLISHED'
        and lower(regexp_replace(coalesce(c.title,'')||' '||coalesce(c.content,''),'[[:space:]]+',' ','g')) ~* regex_pattern;

    elsif rule_row.detector='METADATA' then
      if rule_row.code='RATING_EXPLICIT' and work_row.rating in ('GENERAL','TEEN') then
        metadata_hit:=metadata_text ~* rule_row.pattern_a;

        select count(*)::integer into chapter_hits
        from public.chapters c
        where c.work_id=target_work
          and c.status='PUBLISHED'
          and lower(regexp_replace(coalesce(c.title,'')||' '||coalesce(c.content,''),'[[:space:]]+',' ','g')) ~* rule_row.pattern_a;
      end if;
    end if;

    if metadata_hit or chapter_hits>0 then
      insert into public.moderation_scan_hits(
        scan_id,rule_id,category,label,weight,match_count
      )
      values(
        scan_id,rule_row.id,rule_row.category,rule_row.label,rule_row.weight,
        greatest(1,chapter_hits+(case when metadata_hit then 1 else 0 end))
      )
      on conflict(scan_id,rule_id) do update
      set match_count=excluded.match_count,weight=excluded.weight;

      total_score:=least(100,total_score+rule_row.weight);
      total_signals:=total_signals+1;
    end if;
  end loop;

  severity_value:=case
    when total_score>=80 then 'URGENT'
    when total_score>=55 then 'REVIEW'
    when total_score>=25 then 'WATCH'
    else 'CLEAR'
  end;

  action_value:=case
    when total_score>=80 then 'URGENT_REVIEW'
    when total_score>=55 then 'HUMAN_REVIEW'
    when total_score>=25 then 'WATCH'
    else 'NONE'
  end;

  update public.moderation_scans
  set score=total_score,
      severity=severity_value,
      recommended_action=action_value,
      signals_count=total_signals
  where id=scan_id;

  update public.works
  set moderation_risk_score=total_score,
      moderation_state=severity_value,
      moderation_scan_pending=false,
      last_moderation_scan_at=now()
  where id=target_work;

  if total_score>=55 and not exists(
    select 1 from public.reports r
    where r.work_id=target_work
      and r.reason='NOVASHIELD'
      and r.status in ('OPEN','REVIEWING')
  ) then
    select array_agg(distinct h.category order by h.category) into categories
    from public.moderation_scan_hits h
    where h.scan_id=scan_id;

    insert into public.reports(reporter_id,work_id,reason,details,status)
    values(
      null,
      target_work,
      'NOVASHIELD',
      'NovaShield sinalizou risco '||severity_value||' ('||total_score||'/100). Categorias: '||
        coalesce(array_to_string(categories,', '),'não classificadas')||
        '. Revisão humana obrigatória; nenhum conteúdo foi ocultado automaticamente.',
      'OPEN'
    );
  end if;

  insert into public.audit_log(actor_user_id,action,entity_type,entity_id,metadata)
  values(
    uid,'NOVASHIELD_SCAN','WORK',target_work,
    jsonb_build_object(
      'scan_id',scan_id,'score',total_score,'severity',severity_value,
      'signals',total_signals,'source',left(upper(coalesce(scan_source,'MANUAL')),40)
    )
  );

  return jsonb_build_object(
    'scan_id',scan_id,
    'score',total_score,
    'severity',severity_value,
    'recommended_action',action_value,
    'requires_human_review',total_score>=55
  );
end;
$$;

revoke execute on function public.novashield_scan_work(uuid,text) from public,anon;
grant execute on function public.novashield_scan_work(uuid,text) to authenticated;

create or replace function public.novashield_staff_queue(limit_count integer default 80)
returns jsonb
language plpgsql
stable
security definer
set search_path=public,auth,pg_temp
as $$
declare result jsonb;
begin
  if not public.is_staff() then
    raise exception 'STAFF_ONLY' using errcode='42501';
  end if;

  select jsonb_build_object(
    'pending',coalesce((
      select jsonb_agg(to_jsonb(x) order by x.updated_at desc)
      from (
        select
          w.id,w.title,w.rating,w.status,w.visibility,w.updated_at,
          p.username::text author_username,
          w.moderation_scan_pending,
          w.moderation_risk_score,
          w.moderation_state,
          w.last_moderation_scan_at
        from public.works w
        join public.profiles p on p.id=w.creator_id
        where w.deleted_at is null and w.moderation_scan_pending
        order by w.updated_at desc
        limit greatest(1,least(coalesce(limit_count,80),200))
      ) x
    ),'[]'::jsonb),
    'flagged',coalesce((
      select jsonb_agg(to_jsonb(x) order by x.score desc,x.created_at desc)
      from (
        select distinct on (s.work_id)
          s.id scan_id,s.work_id,s.score,s.severity,s.recommended_action,
          s.review_status,s.created_at,
          w.title,p.username::text author_username,
          coalesce((
            select jsonb_agg(jsonb_build_object(
              'category',h.category,'label',h.label,'weight',h.weight,'matches',h.match_count
            ) order by h.weight desc)
            from public.moderation_scan_hits h
            where h.scan_id=s.id
          ),'[]'::jsonb) signals
        from public.moderation_scans s
        join public.works w on w.id=s.work_id
        join public.profiles p on p.id=w.creator_id
        where s.score>=25 and w.deleted_at is null
        order by s.work_id,s.created_at desc
      ) x
      limit greatest(1,least(coalesce(limit_count,80),200))
    ),'[]'::jsonb)
  )
  into result;

  return result;
end;
$$;

revoke execute on function public.novashield_staff_queue(integer) from public,anon;
grant execute on function public.novashield_staff_queue(integer) to authenticated;

create or replace function public.novashield_review_scan(
  target_scan uuid,
  next_review_status text,
  moderator_note text default null
)
returns void
language plpgsql
security definer
set search_path=public,auth,pg_temp
as $$
declare normalized text:=upper(btrim(coalesce(next_review_status,'')));
declare wid uuid;
begin
  if not public.is_staff() then
    raise exception 'STAFF_ONLY' using errcode='42501';
  end if;

  if normalized not in ('FALSE_POSITIVE','CONFIRMED_SAFE','ACTION_REQUIRED') then
    raise exception 'INVALID_REVIEW_STATUS';
  end if;

  update public.moderation_scans
  set review_status=normalized,
      reviewed_by=auth.uid(),
      review_note=nullif(left(btrim(coalesce(moderator_note,'')),4000),''),
      reviewed_at=now()
  where id=target_scan
  returning work_id into wid;

  if wid is null then raise exception 'SCAN_NOT_FOUND' using errcode='P0002'; end if;

  if normalized in ('FALSE_POSITIVE','CONFIRMED_SAFE') then
    update public.works
    set moderation_state='CLEAR',
        moderation_risk_score=0
    where id=wid;

    update public.reports
    set status='DISMISSED',resolved_at=now()
    where work_id=wid and reason='NOVASHIELD' and status in ('OPEN','REVIEWING');
  end if;

  insert into public.audit_log(actor_user_id,action,entity_type,entity_id,metadata)
  values(
    auth.uid(),'NOVASHIELD_REVIEW','WORK',wid,
    jsonb_build_object('scan_id',target_scan,'decision',normalized,'note',nullif(left(btrim(coalesce(moderator_note,'')),4000),''))
  );
end;
$$;

revoke execute on function public.novashield_review_scan(uuid,text,text) from public,anon;
grant execute on function public.novashield_review_scan(uuid,text,text) to authenticated;

create or replace function public.novashield_admin_rules()
returns jsonb
language plpgsql
stable
security definer
set search_path=public,auth,pg_temp
as $$
begin
  if not public.is_admin() then raise exception 'ADMIN_ONLY' using errcode='42501'; end if;
  return coalesce((
    select jsonb_agg(to_jsonb(r) order by r.weight desc,r.code)
    from public.moderation_scan_rules r
  ),'[]'::jsonb);
end;
$$;

create or replace function public.novashield_admin_set_rule(
  target_rule uuid,
  next_enabled boolean,
  next_weight integer
)
returns void
language plpgsql
security definer
set search_path=public,auth,pg_temp
as $$
begin
  if not public.is_admin() then raise exception 'ADMIN_ONLY' using errcode='42501'; end if;

  update public.moderation_scan_rules
  set enabled=coalesce(next_enabled,false),
      weight=greatest(1,least(coalesce(next_weight,weight),100)),
      updated_by=auth.uid(),
      updated_at=now()
  where id=target_rule;

  if not found then raise exception 'RULE_NOT_FOUND' using errcode='P0002'; end if;

  insert into public.audit_log(actor_user_id,action,entity_type,entity_id,metadata)
  values(auth.uid(),'NOVASHIELD_RULE_UPDATED','MODERATION_RULE',target_rule,
    jsonb_build_object('enabled',coalesce(next_enabled,false),'weight',next_weight));
end;
$$;

revoke execute on function public.novashield_admin_rules() from public,anon;
revoke execute on function public.novashield_admin_set_rule(uuid,boolean,integer) from public,anon;
grant execute on function public.novashield_admin_rules() to authenticated;
grant execute on function public.novashield_admin_set_rule(uuid,boolean,integer) to authenticated;

-- =============================================================================
-- NovaCare — SAC
-- =============================================================================

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  contact_email citext,
  category varchar(30) not null check (category in (
    'ACCOUNT','CONTENT','BUG','MODERATION','PRIVACY','BILLING','SUGGESTION','OTHER'
  )),
  priority varchar(20) not null default 'NORMAL'
    check (priority in ('LOW','NORMAL','HIGH','URGENT')),
  status varchar(24) not null default 'OPEN'
    check (status in ('OPEN','WAITING_USER','IN_PROGRESS','RESOLVED','CLOSED')),
  subject varchar(180) not null,
  assigned_to uuid references public.profiles(id) on delete set null,
  last_message_at timestamptz not null default now(),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  author_id uuid references public.profiles(id) on delete set null,
  author_role varchar(20) not null check (author_role in ('USER','STAFF','SYSTEM')),
  body text not null check (char_length(body) between 1 and 12000),
  created_at timestamptz not null default now()
);

create index if not exists support_tickets_requester_updated_idx
  on public.support_tickets(requester_id,updated_at desc);
create index if not exists support_tickets_queue_idx
  on public.support_tickets(status,priority,last_message_at desc);
create index if not exists support_tickets_assigned_idx
  on public.support_tickets(assigned_to,status)
  where assigned_to is not null;
create index if not exists support_messages_ticket_created_idx
  on public.support_ticket_messages(ticket_id,created_at);

alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;

drop policy if exists support_tickets_owner_staff_read on public.support_tickets;
create policy support_tickets_owner_staff_read
on public.support_tickets for select to authenticated
using (requester_id=(select auth.uid()) or public.is_staff());

drop policy if exists support_messages_owner_staff_read on public.support_ticket_messages;
create policy support_messages_owner_staff_read
on public.support_ticket_messages for select to authenticated
using (
  exists(
    select 1 from public.support_tickets t
    where t.id=ticket_id
      and (t.requester_id=(select auth.uid()) or public.is_staff())
  )
);

revoke insert,update,delete on public.support_tickets from anon,authenticated;
revoke insert,update,delete on public.support_ticket_messages from anon,authenticated;
grant select on public.support_tickets to authenticated;
grant select on public.support_ticket_messages to authenticated;
grant all on public.support_tickets to service_role;
grant all on public.support_ticket_messages to service_role;

drop trigger if exists support_tickets_updated_at on public.support_tickets;
create trigger support_tickets_updated_at
before update on public.support_tickets
for each row execute function public.set_updated_at();

create or replace function public.create_support_ticket(
  ticket_category text,
  ticket_subject text,
  ticket_body text
)
returns bigint
language plpgsql
security definer
set search_path=public,auth,pg_temp
as $$
declare
  uid uuid:=auth.uid();
  normalized_category text:=upper(btrim(coalesce(ticket_category,'OTHER')));
  ticket_id bigint;
  email_value citext;
begin
  if uid is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  if normalized_category not in ('ACCOUNT','CONTENT','BUG','MODERATION','PRIVACY','BILLING','SUGGESTION','OTHER') then
    raise exception 'INVALID_CATEGORY';
  end if;
  if char_length(btrim(coalesce(ticket_subject,''))) not between 4 and 180 then
    raise exception 'INVALID_SUBJECT';
  end if;
  if char_length(btrim(coalesce(ticket_body,''))) not between 10 and 12000 then
    raise exception 'INVALID_BODY';
  end if;

  perform public.consume_rate_limit(uid,'SUPPORT_TICKET',4,3600,ticket_subject);

  select u.email::citext into email_value from auth.users u where u.id=uid;

  insert into public.support_tickets(
    requester_id,contact_email,category,subject
  )
  values(
    uid,email_value,normalized_category,btrim(ticket_subject)
  )
  returning id into ticket_id;

  insert into public.support_ticket_messages(ticket_id,author_id,author_role,body)
  values(ticket_id,uid,'USER',btrim(ticket_body));

  insert into public.audit_log(actor_user_id,action,entity_type,entity_id,metadata)
  values(uid,'SUPPORT_TICKET_CREATED','SUPPORT_TICKET',null,
    jsonb_build_object('ticket_id',ticket_id,'category',normalized_category));

  return ticket_id;
end;
$$;

create or replace function public.my_support_tickets()
returns jsonb
language plpgsql
stable
security definer
set search_path=public,auth,pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',t.id,
      'code','AN-'||lpad(t.id::text,6,'0'),
      'category',t.category,
      'priority',t.priority,
      'status',t.status,
      'subject',t.subject,
      'last_message_at',t.last_message_at,
      'created_at',t.created_at,
      'unread_staff_messages',(
        select count(*)
        from public.support_ticket_messages m
        where m.ticket_id=t.id and m.author_role='STAFF'
          and m.created_at>coalesce((
            select max(m2.created_at)
            from public.support_ticket_messages m2
            where m2.ticket_id=t.id and m2.author_id=auth.uid()
          ),t.created_at)
      )
    ) order by t.last_message_at desc)
    from public.support_tickets t
    where t.requester_id=auth.uid()
  ),'[]'::jsonb);
end;
$$;

create or replace function public.get_support_ticket(target_ticket bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path=public,auth,pg_temp
as $$
declare result jsonb;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;

  select jsonb_build_object(
    'ticket',jsonb_build_object(
      'id',t.id,
      'code','AN-'||lpad(t.id::text,6,'0'),
      'category',t.category,
      'priority',t.priority,
      'status',t.status,
      'subject',t.subject,
      'assigned_to',t.assigned_to,
      'created_at',t.created_at,
      'updated_at',t.updated_at
    ),
    'messages',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',m.id,
        'author_role',m.author_role,
        'author_username',p.username::text,
        'author_display_name',coalesce(p.display_name,p.username::text),
        'body',m.body,
        'created_at',m.created_at
      ) order by m.created_at)
      from public.support_ticket_messages m
      left join public.profiles p on p.id=m.author_id
      where m.ticket_id=t.id
    ),'[]'::jsonb)
  )
  into result
  from public.support_tickets t
  where t.id=target_ticket
    and (t.requester_id=auth.uid() or public.is_staff());

  if result is null then raise exception 'TICKET_NOT_FOUND' using errcode='P0002'; end if;
  return result;
end;
$$;

create or replace function public.reply_support_ticket(
  target_ticket bigint,
  message_body text
)
returns bigint
language plpgsql
security definer
set search_path=public,auth,pg_temp
as $$
declare
  uid uuid:=auth.uid();
  staff boolean;
  owner boolean;
  next_id bigint;
  current_status text;
begin
  if uid is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  if char_length(btrim(coalesce(message_body,''))) not between 1 and 12000 then raise exception 'INVALID_BODY'; end if;

  staff:=public.is_staff();

  select t.requester_id=uid,t.status
  into owner,current_status
  from public.support_tickets t
  where t.id=target_ticket;

  if coalesce(owner,false)=false and not staff then raise exception 'NO_ACCESS' using errcode='42501'; end if;
  if current_status='CLOSED' and not staff then raise exception 'TICKET_CLOSED'; end if;

  perform public.consume_rate_limit(uid,'SUPPORT_REPLY',12,3600,message_body);

  insert into public.support_ticket_messages(ticket_id,author_id,author_role,body)
  values(target_ticket,uid,case when staff then 'STAFF' else 'USER' end,btrim(message_body))
  returning id into next_id;

  update public.support_tickets
  set last_message_at=now(),
      status=case
        when staff then 'WAITING_USER'
        when status in ('RESOLVED','WAITING_USER') then 'OPEN'
        else status
      end,
      closed_at=null
  where id=target_ticket;

  return next_id;
end;
$$;

create or replace function public.support_staff_queue(
  status_filter text default null,
  limit_count integer default 100
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public,auth,pg_temp
as $$
begin
  if not public.is_staff() then raise exception 'STAFF_ONLY' using errcode='42501'; end if;

  return coalesce((
    select jsonb_agg(to_jsonb(x) order by x.priority_rank,x.last_message_at desc)
    from (
      select
        t.id,
        'AN-'||lpad(t.id::text,6,'0') code,
        t.category,t.priority,t.status,t.subject,t.assigned_to,
        t.last_message_at,t.created_at,
        p.username::text requester_username,
        coalesce(p.display_name,p.username::text) requester_display_name,
        a.username::text assigned_username,
        case t.priority when 'URGENT' then 1 when 'HIGH' then 2 when 'NORMAL' then 3 else 4 end priority_rank,
        (select count(*) from public.support_ticket_messages m where m.ticket_id=t.id) message_count
      from public.support_tickets t
      join public.profiles p on p.id=t.requester_id
      left join public.profiles a on a.id=t.assigned_to
      where status_filter is null or upper(status_filter)=t.status
      order by priority_rank,t.last_message_at desc
      limit greatest(1,least(coalesce(limit_count,100),250))
    ) x
  ),'[]'::jsonb);
end;
$$;

create or replace function public.support_staff_update_ticket(
  target_ticket bigint,
  next_status text default null,
  next_priority text default null,
  assign_to_self boolean default false
)
returns void
language plpgsql
security definer
set search_path=public,auth,pg_temp
as $$
declare
  normalized_status text:=upper(nullif(btrim(coalesce(next_status,'')),''));
  normalized_priority text:=upper(nullif(btrim(coalesce(next_priority,'')),''));
begin
  if not public.is_staff() then raise exception 'STAFF_ONLY' using errcode='42501'; end if;

  if normalized_status is not null and normalized_status not in ('OPEN','WAITING_USER','IN_PROGRESS','RESOLVED','CLOSED') then
    raise exception 'INVALID_STATUS';
  end if;
  if normalized_priority is not null and normalized_priority not in ('LOW','NORMAL','HIGH','URGENT') then
    raise exception 'INVALID_PRIORITY';
  end if;

  update public.support_tickets
  set status=coalesce(normalized_status,status),
      priority=coalesce(normalized_priority,priority),
      assigned_to=case when assign_to_self then auth.uid() else assigned_to end,
      closed_at=case
        when normalized_status in ('RESOLVED','CLOSED') then now()
        when normalized_status is not null then null
        else closed_at
      end,
      updated_at=now()
  where id=target_ticket;

  if not found then raise exception 'TICKET_NOT_FOUND' using errcode='P0002'; end if;

  insert into public.audit_log(actor_user_id,action,entity_type,entity_id,metadata)
  values(auth.uid(),'SUPPORT_TICKET_UPDATED','SUPPORT_TICKET',null,
    jsonb_build_object(
      'ticket_id',target_ticket,'status',normalized_status,
      'priority',normalized_priority,'assign_to_self',assign_to_self
    ));
end;
$$;

revoke execute on function public.create_support_ticket(text,text,text) from public,anon;
revoke execute on function public.my_support_tickets() from public,anon;
revoke execute on function public.get_support_ticket(bigint) from public,anon;
revoke execute on function public.reply_support_ticket(bigint,text) from public,anon;
revoke execute on function public.support_staff_queue(text,integer) from public,anon;
revoke execute on function public.support_staff_update_ticket(bigint,text,text,boolean) from public,anon;

grant execute on function public.create_support_ticket(text,text,text) to authenticated;
grant execute on function public.my_support_tickets() to authenticated;
grant execute on function public.get_support_ticket(bigint) to authenticated;
grant execute on function public.reply_support_ticket(bigint,text) to authenticated;
grant execute on function public.support_staff_queue(text,integer) to authenticated;
grant execute on function public.support_staff_update_ticket(bigint,text,text,boolean) to authenticated;

-- =============================================================================
-- ArchiveNova Classics
-- =============================================================================

create table if not exists public.classic_books (
  id uuid primary key default gen_random_uuid(),
  slug varchar(180) not null unique,
  title varchar(300) not null,
  author_name varchar(240) not null,
  language varchar(16) not null default 'pt-BR',
  summary text not null default '',
  original_publication varchar(240),
  source_name varchar(120) not null,
  source_url text not null,
  source_id varchar(120),
  copyright_note text not null,
  cover_url text,
  published boolean not null default false,
  word_count bigint not null default 0 check (word_count>=0),
  chapter_count integer not null default 0 check (chapter_count>=0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.classic_chapters (
  id uuid primary key default gen_random_uuid(),
  book_id uuid not null references public.classic_books(id) on delete cascade,
  chapter_number integer not null check (chapter_number>0),
  title varchar(300),
  content_text text not null,
  word_count integer not null default 0 check (word_count>=0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(book_id,chapter_number)
);

create index if not exists classic_books_published_title_idx
  on public.classic_books(published,title);
create index if not exists classic_chapters_book_number_idx
  on public.classic_chapters(book_id,chapter_number);

alter table public.classic_books enable row level security;
alter table public.classic_chapters enable row level security;

drop policy if exists classic_books_public_read on public.classic_books;
create policy classic_books_public_read
on public.classic_books for select to anon,authenticated
using (published or public.is_admin());

drop policy if exists classic_chapters_public_read on public.classic_chapters;
create policy classic_chapters_public_read
on public.classic_chapters for select to anon,authenticated
using (
  exists(
    select 1 from public.classic_books b
    where b.id=book_id and (b.published or public.is_admin())
  )
);

revoke insert,update,delete on public.classic_books from anon,authenticated;
revoke insert,update,delete on public.classic_chapters from anon,authenticated;
grant select on public.classic_books to anon,authenticated;
grant select on public.classic_chapters to anon,authenticated;
grant all on public.classic_books to service_role;
grant all on public.classic_chapters to service_role;

drop trigger if exists classic_books_updated_at on public.classic_books;
create trigger classic_books_updated_at
before update on public.classic_books
for each row execute function public.set_updated_at();

drop trigger if exists classic_chapters_updated_at on public.classic_chapters;
create trigger classic_chapters_updated_at
before update on public.classic_chapters
for each row execute function public.set_updated_at();

create or replace function public.refresh_classic_book_totals()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare bid uuid;
begin
  bid:=case when tg_op='DELETE' then old.book_id else new.book_id end;

  update public.classic_books b
  set chapter_count=(
        select count(*) from public.classic_chapters c where c.book_id=bid
      ),
      word_count=(
        select coalesce(sum(c.word_count),0) from public.classic_chapters c where c.book_id=bid
      ),
      updated_at=now()
  where b.id=bid;

  if tg_op='DELETE' then return old; end if;
  return new;
end;
$$;

create or replace function public.prepare_classic_chapter()
returns trigger
language plpgsql
set search_path=public,pg_temp
as $$
begin
  new.word_count:=public.count_words(new.content_text);
  return new;
end;
$$;

drop trigger if exists classic_chapters_prepare on public.classic_chapters;
create trigger classic_chapters_prepare
before insert or update of content_text on public.classic_chapters
for each row execute function public.prepare_classic_chapter();

drop trigger if exists classic_chapters_refresh_totals on public.classic_chapters;
create trigger classic_chapters_refresh_totals
after insert or update or delete on public.classic_chapters
for each row execute function public.refresh_classic_book_totals();

revoke execute on function public.refresh_classic_book_totals() from public,anon,authenticated;
revoke execute on function public.prepare_classic_chapter() from public,anon,authenticated;

create or replace function public.classics_catalog()
returns jsonb
language sql
stable
security definer
set search_path=public,pg_temp
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',b.id,'slug',b.slug,'title',b.title,'author_name',b.author_name,
    'language',b.language,'summary',b.summary,'original_publication',b.original_publication,
    'source_name',b.source_name,'source_url',b.source_url,'source_id',b.source_id,
    'copyright_note',b.copyright_note,'cover_url',b.cover_url,
    'word_count',b.word_count,'chapter_count',b.chapter_count,'updated_at',b.updated_at
  ) order by b.title),'[]'::jsonb)
  from public.classic_books b
  where b.published;
$$;

create or replace function public.get_classic_book(book_slug text)
returns jsonb
language plpgsql
stable
security definer
set search_path=public,pg_temp
as $$
declare result jsonb;
begin
  select jsonb_build_object(
    'book',jsonb_build_object(
      'id',b.id,'slug',b.slug,'title',b.title,'author_name',b.author_name,
      'language',b.language,'summary',b.summary,'original_publication',b.original_publication,
      'source_name',b.source_name,'source_url',b.source_url,'source_id',b.source_id,
      'copyright_note',b.copyright_note,'cover_url',b.cover_url,
      'word_count',b.word_count,'chapter_count',b.chapter_count,'updated_at',b.updated_at
    ),
    'chapters',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',c.id,'chapter_number',c.chapter_number,'title',c.title,'word_count',c.word_count
      ) order by c.chapter_number)
      from public.classic_chapters c
      where c.book_id=b.id
    ),'[]'::jsonb)
  )
  into result
  from public.classic_books b
  where b.slug=book_slug and b.published;

  if result is null then raise exception 'CLASSIC_NOT_FOUND' using errcode='P0002'; end if;
  return result;
end;
$$;

create or replace function public.get_classic_chapter(
  book_slug text,
  target_chapter integer
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public,pg_temp
as $$
declare result jsonb;
begin
  select jsonb_build_object(
    'book',jsonb_build_object(
      'slug',b.slug,'title',b.title,'author_name',b.author_name,'chapter_count',b.chapter_count
    ),
    'chapter',jsonb_build_object(
      'id',c.id,'chapter_number',c.chapter_number,'title',c.title,
      'content_text',c.content_text,'word_count',c.word_count
    )
  )
  into result
  from public.classic_books b
  join public.classic_chapters c on c.book_id=b.id
  where b.slug=book_slug and b.published and c.chapter_number=target_chapter;

  if result is null then raise exception 'CLASSIC_CHAPTER_NOT_FOUND' using errcode='P0002'; end if;
  return result;
end;
$$;

revoke execute on function public.classics_catalog() from public;
revoke execute on function public.get_classic_book(text) from public;
revoke execute on function public.get_classic_chapter(text,integer) from public;
grant execute on function public.classics_catalog() to anon,authenticated;
grant execute on function public.get_classic_book(text) to anon,authenticated;
grant execute on function public.get_classic_chapter(text,integer) to anon,authenticated;

-- Add NovaDrop 02 runtime flags.
insert into public.platform_feature_flags(key,enabled,description)
values
  ('novashield',true,'NovaShield: triagem explicável de risco para moderação'),
  ('novacare',true,'NovaCare: SAC e tickets dentro do Archive Nova'),
  ('nova_fx',true,'NovaFX: efeitos visuais progressivos e otimizados'),
  ('classics',true,'ArchiveNova Classics: obras em domínio público')
on conflict(key) do update
set description=excluded.description;

-- Active-account enforcement for new user-writable support tables.
drop trigger if exists support_tickets_active_account_guard on public.support_tickets;
create trigger support_tickets_active_account_guard
before insert or update or delete on public.support_tickets
for each row execute function public.enforce_active_account_write();

drop trigger if exists support_messages_active_account_guard on public.support_ticket_messages;
create trigger support_messages_active_account_guard
before insert or update or delete on public.support_ticket_messages
for each row execute function public.enforce_active_account_write();
